<?php
/**
 * M2B E-book PDF Watermark Helper
 * Generates personalized watermarked PDFs per buyer using FPDI
 * 
 * Updated: March 2026
 */

// Composer autoload (if not already loaded)
$autoloadPath = __DIR__ . '/vendor/autoload.php';
if (file_exists($autoloadPath) && !class_exists('setasign\Fpdi\Fpdi')) {
    require_once $autoloadPath;
}

use setasign\Fpdi\Fpdi;
use setasign\Fpdf\Fpdf;

class PDFWatermark {
    private $watermarkText;
    private $outputDir;
    
    public function __construct() {
        $this->outputDir = __DIR__ . '/temp';
        
        // Create temp directory if not exists
        if (!is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0755, true);
        }
    }
    
    /**
     * Add watermark to PDF
     * On shared hosting, creates watermark info file instead
     */
    public function addWatermark($inputPdf, $outputPdf, $buyerName, $buyerEmail) {
        $timestamp = date('Y-m-d H:i:s');
        $year = date('Y');
        
        // Create watermark text
        $this->watermarkText = "© {$year} {$buyerName} | {$buyerEmail}";
        $ebookTitle = defined('EBOOK_TITLE') ? EBOOK_TITLE : 'Panduan Global Export & Import untuk Indonesia';
        
        // Try to use FPDI if available
        if (class_exists('setasign\Fpdi\Fpdi')) {
            return $this->applyWatermarkWithFpdi($inputPdf, $outputPdf, $buyerName, $buyerEmail);
        }
        
        // Fallback: Create watermark info file
        $watermarkInfo = $this->createWatermarkInfoFile($inputPdf, $outputPdf, $buyerName, $buyerEmail, $timestamp);
        
        // Copy original PDF to temp (for manual watermarking)
        if (file_exists($inputPdf)) {
            copy($inputPdf, $outputPdf);
        }
        
        return $watermarkInfo;
    }
    
    /**
     * Create watermark info file for manual application
     */
    private function createWatermarkInfoFile($inputPdf, $outputPdf, $buyerName, $buyerEmail, $timestamp) {
        $year = date('Y');
        $ebookTitle = defined('EBOOK_TITLE') ? EBOOK_TITLE : 'Panduan Global Export & Import untuk Indonesia';
        
        $infoContent = <<<INFO
========================================
M2B E-BOOK WATERMARK INFORMATION
========================================

Order Details:
--------------
Buyer Name: {$buyerName}
Buyer Email: {$buyerEmail}
Generated: {$timestamp}
Source PDF: {$inputPdf}
Output PDF: {$outputPdf}

Watermark Text (to be applied to all pages):
--------------------------------------------
Line 1: © {$year} {$buyerName} | {$buyerEmail}
Line 2: {$ebookTitle} - M2B

Watermark Specifications:
-------------------------
Position: Bottom Center
Font: Arial or similar sans-serif
Font Size: 10pt
Color: #666666 (Gray)
Opacity: 50%

Recommended Tools for Manual Watermarking:
------------------------------------------
- Adobe Acrobat Pro
- PDFescape (online)
- Sejda PDF (online)
- iLovePDF (online)
- PDF-XChange Editor

Instructions:
-------------
1. Open the PDF in your preferred editor
2. Add a text watermark to ALL pages
3. Use the watermark text specified above
4. Position at bottom center
5. Set opacity to 50%
6. Save the watermarked PDF

========================================
Generated by M2B E-book System
https://m2b.co.id
========================================
INFO;
        
        // Extract filename without extension
        $outputBasename = pathinfo($outputPdf, PATHINFO_FILENAME);
        $infoFile = $this->outputDir . '/' . $outputBasename . '_watermark_info.txt';
        
        file_put_contents($infoFile, $infoContent);
        
        return [
            'success' => true,
            'method' => 'manual',
            'watermark_text' => "© {$year} {$buyerName} | {$buyerEmail}",
            'info_file' => $infoFile,
            'message' => 'Watermark info file created. Apply watermark manually using PDF editor.'
        ];
    }
    
    /**
     * Decompress PDF using Ghostscript for FPDI compatibility
     */
    private function decompressPdf($inputPdf) {
        $decompressed = $this->outputDir . '/decomp_' . md5($inputPdf) . '.pdf';
        
        // Cache: reuse if already decompressed and source hasn't changed
        if (file_exists($decompressed) && filemtime($decompressed) >= filemtime($inputPdf)) {
            return $decompressed;
        }
        
        $gsPath = '/usr/bin/gs';
        if (!file_exists($gsPath)) {
            return null;
        }
        
        $cmd = escapeshellcmd($gsPath) 
            . ' -dBATCH -dNOPAUSE -dQUIET -sDEVICE=pdfwrite -dCompatibilityLevel=1.4'
            . ' -sOutputFile=' . escapeshellarg($decompressed) 
            . ' ' . escapeshellarg($inputPdf);
        
        // Use proc_open since exec/shell_exec are disabled on shared hosting
        $descriptors = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];
        
        $process = proc_open($cmd, $descriptors, $pipes);
        if (!is_resource($process)) {
            error_log('Ghostscript: proc_open failed');
            return null;
        }
        
        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $returnCode = proc_close($process);
        
        if ($returnCode !== 0 || !file_exists($decompressed)) {
            error_log('Ghostscript decompress failed (code ' . $returnCode . '): ' . $stderr);
            return null;
        }
        
        return $decompressed;
    }
    
    /**
     * Apply watermark using Ghostscript + FPDI
     */
    private function applyWatermarkWithFpdi($inputPdf, $outputPdf, $buyerName, $buyerEmail) {
        try {
            // Decompress PDF first for FPDI compatibility
            $sourcePdf = $this->decompressPdf($inputPdf);
            if (!$sourcePdf) {
                $sourcePdf = $inputPdf; // Try original if gs fails
            }
            
            $pdf = new Fpdi();
            $pdf->SetAutoPageBreak(false);
            $pageCount = $pdf->setSourceFile($sourcePdf);
            $year = date('Y');
            $watermarkText = iconv('UTF-8', 'ISO-8859-1//TRANSLIT', "(c) {$year} {$buyerName} | {$buyerEmail}");
            
            for ($pageNo = 1; $pageNo <= $pageCount; $pageNo++) {
                $templateId = $pdf->importPage($pageNo);
                $size = $pdf->getTemplateSize($templateId);
                
                $pdf->AddPage($size['orientation'], [$size['width'], $size['height']]);
                $pdf->useTemplate($templateId);
                
                // Add watermark at bottom center
                $pdf->SetFont('Arial', '', 9);
                $pdf->SetTextColor(128, 128, 128);
                $pdf->SetXY(10, $size['height'] - 12);
                $pdf->Cell($size['width'] - 20, 10, $watermarkText, 0, 0, 'C');
            }
            
            $pdf->Output($outputPdf, 'F');
            
            return [
                'success' => true,
                'method' => 'fpdi',
                'watermark_text' => "© {$year} {$buyerName} | {$buyerEmail}",
                'output_file' => $outputPdf,
                'page_count' => $pageCount,
                'message' => 'Watermark applied successfully'
            ];
            
        } catch (\Throwable $e) {
            error_log('FPDI Watermark Error: ' . $e->getMessage());
            
            // Fallback to info file
            return $this->createWatermarkInfoFile($inputPdf, $outputPdf, $buyerName, $buyerEmail, date('Y-m-d H:i:s'));
        }
    }
    
    /**
     * Get watermark text
     */
    public function getWatermarkText() {
        return $this->watermarkText;
    }
    
    /**
     * Clean up old temp files (older than 24 hours)
     */
    public function cleanupOldFiles() {
        $files = glob($this->outputDir . '/*');
        $now = time();
        
        foreach ($files as $file) {
            if (is_file($file)) {
                if ($now - filemtime($file) >= 86400) { // 24 hours
                    unlink($file);
                }
            }
        }
    }
}
